# Generated by Django 5.2.10 on 2026-02-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_expiry',
        ),
    ]
