# Generated by Django 5.2.10 on 2026-02-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_membership_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='Fullname',
        ),
    ]
