# Generated by Django 5.2.10 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_full_name_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ads_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
