# Generated by Django 5.2.10 on 2026-02-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_ads_provided_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Fullname',
            new_name='name',
        ),
    ]
