# Generated by Django 5.2.10 on 2026-02-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='has_claimed_referral',
            field=models.BooleanField(default=False),
        ),
    ]
