# Generated by Django 5.2.10 on 2026-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savings_comparison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='savings_coupons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_lifetime_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
