# Generated by Django 5.2.10 on 2026-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_referral_reward_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
