# Generated by Django 5.2.10 on 2026-06-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=99),
        ),
    ]
