# Generated by Django 5.2.10 on 2026-07-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_sitesettings_referral_reward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cookie_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
