# Generated by Django 5.2.10 on 2026-07-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_cookie_consent_user_cookie_consent_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
