# Generated by Django 5.2.10 on 2026-07-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_delete_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Amount in USD added to the referrer's account balance when a referred user subscribes and completes their first purchase.", max_digits=10, verbose_name='Referral Reward Amount ($)'),
        ),
    ]
