# Generated by Django 5.2.10 on 2026-03-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='bkash_number',
        ),
    ]
