# Generated by Django 5.2.10 on 2026-05-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productreview_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='sellerrequest',
            old_name='shop_description',
            new_name='experience_description',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='business_reg_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='digital_signature_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='estimated_sku_count',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='fulfillment_method',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='legal_business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='legal_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='own_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='price_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='product_condition',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='return_policy_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='return_policy_document',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/policies/'),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='shipping_regions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/utility/'),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
