# Generated by Django 5.2.10 on 2026-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0014_alter_product_rating'),
        ('store', '0005_alter_sellerrequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerrequest',
            old_name='legal_full_name',
            new_name='contact_full_name',
        ),
        migrations.RenameField(
            model_name='sellerrequest',
            old_name='own_inventory',
            new_name='owns_inventory',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='business_document',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='digital_signature_name',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='fulfillment_method',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='nid_document',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='product_condition',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='agreed_to_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='agreed_to_prohibited_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/licenses/'),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='seller_requests', to='api_integration.category'),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='fulfillment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/ids/'),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='has_prior_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='product_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='business_reg_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='estimated_sku_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='experience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='legal_business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='return_policy_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerrequest',
            name='shipping_regions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
