# Generated by Django 5.2.10 on 2026-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_legal_full_name_sellerrequest_contact_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='bank_name',
            new_name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
