# Generated by Django 5.2.10 on 2026-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_final_price_order_item_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
