# Generated by Django 5.2.10 on 2026-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='local_delivery_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='local_pickup_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='order_processing_time',
            field=models.CharField(default='1-2 Business Days', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='preferred_couriers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='standard_shipping_active',
            field=models.BooleanField(default=True),
        ),
    ]
