# Generated by Django 5.2.10 on 2026-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sellerprofile_local_delivery_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='delivery_radius',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='delivery_timeframe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_address_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_address_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
