# Generated by Django 5.2.10 on 2026-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_status_alter_sellerproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='agreed_to_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='agreed_to_seller_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
