# Generated by Django 5.2.10 on 2026-06-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0015_notification_pricealert'),
        ('store', '0017_sellerrequest_agreed_to_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api_integration.productlisting'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.sellerproduct'),
        ),
    ]
