# Generated by Django 5.2.10 on 2026-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_listing_alter_order_seller_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
