# Generated by Django 5.2.10 on 2026-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_sellerproduct_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='return_policy_description',
        ),
        migrations.RemoveField(
            model_name='sellerrequest',
            name='return_policy_document',
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='agree_return_policy',
            field=models.BooleanField(default=False),
        ),
    ]
