# Generated by Django 5.2.10 on 2026-08-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0016_delete_notification'),
        ('store', '0020_remove_sellerrequest_return_policy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api_integration.productlisting'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.sellerproduct'),
        ),
    ]
