# Generated by Django 5.2.10 on 2026-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0002_adreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpc_amount', models.DecimalField(decimal_places=2, default=0.5, help_text='per click amount to charge advertisers', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Setting',
                'verbose_name_plural': 'Ad Settings',
            },
        ),
        migrations.AddField(
            model_name='customad',
            name='target_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
