# Generated by Django 5.2.10 on 2026-03-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0004_alter_customad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customad',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
