# Generated by Django 5.2.10 on 2026-03-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0005_alter_customad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adreview',
            name='title',
            field=models.CharField(blank=True, help_text='Reject Title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adreview',
            name='feedback',
            field=models.TextField(help_text='Reject Reason'),
        ),
    ]
