# Generated by Django 5.2.10 on 2026-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0006_adreview_title_alter_adreview_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adreview',
            name='title',
        ),
        migrations.AlterField(
            model_name='adreview',
            name='feedback',
            field=models.TextField(),
        ),
    ]
