# Generated by Django 5.2.10 on 2026-03-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0007_remove_adreview_title_alter_adreview_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='custom_ads.customad')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('ad', 'date')},
            },
        ),
    ]
