# Generated by Django 5.2.10 on 2026-04-11 22:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0009_alter_customad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsetting',
            name='cpc_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='per click amount to charge advertisers', max_digits=10),
        ),
    ]
