# Generated by Django 5.2.10 on 2026-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0010_alter_adsetting_cpc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customad',
            name='image',
            field=models.ImageField(help_text='Ideal size: 1280x720px (16:9), Max 10MB. Formats: JPG, PNG, GIF', upload_to='ads/'),
        ),
    ]
