--
-- PostgreSQL database dump
--

\restrict dFDP4doLarASn0gtGox2kZWA87Tg9ZL72D9nkKXxlvP4KxZHN86fgrcAofloam8

-- Dumped from database version 16.12 (Debian 16.12-1.pgdg13+1)
-- Dumped by pg_dump version 16.12 (Debian 16.12-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_profile; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.account_profile (
    id bigint NOT NULL,
    address text,
    interests text,
    profile_picture character varying(100),
    user_id bigint NOT NULL
);


ALTER TABLE public.account_profile OWNER TO dealnux_user;

--
-- Name: account_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.account_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_user; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.account_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    name character varying(255) NOT NULL,
    address text,
    ads_provided boolean NOT NULL,
    referral_code character varying(12),
    balance numeric(10,2) NOT NULL,
    has_claimed_referral boolean NOT NULL,
    referred_by_id bigint,
    otp character varying(4),
    profile_setup_completed boolean NOT NULL
);


ALTER TABLE public.account_user OWNER TO dealnux_user;

--
-- Name: account_user_groups; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.account_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.account_user_groups OWNER TO dealnux_user;

--
-- Name: account_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.account_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_user_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.account_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_user_user_permissions; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.account_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.account_user_user_permissions OWNER TO dealnux_user;

--
-- Name: account_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.account_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_category; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_category (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    parent_id bigint
);


ALTER TABLE public.api_integration_category OWNER TO dealnux_user;

--
-- Name: api_integration_category_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_platform; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_platform (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    code character varying(20) NOT NULL,
    logo character varying(100) NOT NULL,
    api_enabled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.api_integration_platform OWNER TO dealnux_user;

--
-- Name: api_integration_platform_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_platform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_platform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_pricehistory; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_pricehistory (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    currency character varying(10) NOT NULL,
    recorded_at timestamp with time zone NOT NULL,
    listing_id bigint NOT NULL
);


ALTER TABLE public.api_integration_pricehistory OWNER TO dealnux_user;

--
-- Name: api_integration_pricehistory_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_pricehistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_pricehistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_product; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_product (
    id bigint NOT NULL,
    title character varying(500) NOT NULL,
    slug character varying(500) NOT NULL,
    description text NOT NULL,
    brand character varying(200) NOT NULL,
    model_number character varying(200) NOT NULL,
    main_image character varying(1000) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_synced timestamp with time zone NOT NULL,
    category_id bigint
);


ALTER TABLE public.api_integration_product OWNER TO dealnux_user;

--
-- Name: api_integration_product_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_productimage; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_productimage (
    id bigint NOT NULL,
    image_url character varying(1000) NOT NULL,
    alt_text character varying(500) NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.api_integration_productimage OWNER TO dealnux_user;

--
-- Name: api_integration_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_productlisting; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_productlisting (
    id bigint NOT NULL,
    external_id character varying(200) NOT NULL,
    external_url character varying(1000) NOT NULL,
    price numeric(10,2) NOT NULL,
    currency character varying(10) NOT NULL,
    original_price numeric(10,2),
    discount_percentage numeric(5,2),
    condition character varying(20) NOT NULL,
    quantity integer NOT NULL,
    seller_username character varying(200) NOT NULL,
    seller_rating numeric(5,2),
    seller_feedback_count integer NOT NULL,
    item_location character varying(500) NOT NULL,
    ships_from_country character varying(10) NOT NULL,
    shipping_cost numeric(10,2) NOT NULL,
    shipping_currency character varying(10) NOT NULL,
    free_shipping boolean NOT NULL,
    estimated_delivery_days integer,
    returns_accepted boolean NOT NULL,
    return_period_days integer,
    is_available boolean NOT NULL,
    last_checked timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    platform_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.api_integration_productlisting OWNER TO dealnux_user;

--
-- Name: api_integration_productlisting_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_productlisting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_productlisting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_integration_productspecification; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.api_integration_productspecification (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    value character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.api_integration_productspecification OWNER TO dealnux_user;

--
-- Name: api_integration_productspecification_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.api_integration_productspecification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_integration_productspecification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO dealnux_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO dealnux_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO dealnux_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_ads_adreview; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.custom_ads_adreview (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    feedback text NOT NULL,
    reviewed_at timestamp with time zone NOT NULL,
    ad_id bigint NOT NULL,
    reviewer_id bigint
);


ALTER TABLE public.custom_ads_adreview OWNER TO dealnux_user;

--
-- Name: custom_ads_adreview_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.custom_ads_adreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_ads_adreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_ads_advertiserrequest; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.custom_ads_advertiserrequest (
    id bigint NOT NULL,
    business_name character varying(255) NOT NULL,
    business_details text NOT NULL,
    website character varying(200),
    applied_at timestamp with time zone NOT NULL,
    is_reviewed boolean NOT NULL,
    reviewed_at timestamp with time zone,
    rejection_reason text,
    user_id bigint NOT NULL
);


ALTER TABLE public.custom_ads_advertiserrequest OWNER TO dealnux_user;

--
-- Name: custom_ads_advertiserrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.custom_ads_advertiserrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_ads_advertiserrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_ads_customad; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.custom_ads_customad (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    image character varying(100) NOT NULL,
    target_url character varying(200) NOT NULL,
    total_budget numeric(10,2) NOT NULL,
    spent_amount numeric(10,2) NOT NULL,
    priority_weight integer NOT NULL,
    is_premium boolean NOT NULL,
    clicks integer NOT NULL,
    impressions integer NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    is_approved boolean NOT NULL,
    status character varying(10) NOT NULL,
    cta_text character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    advertiser_id bigint NOT NULL,
    CONSTRAINT custom_ads_customad_clicks_check CHECK ((clicks >= 0)),
    CONSTRAINT custom_ads_customad_impressions_check CHECK ((impressions >= 0)),
    CONSTRAINT custom_ads_customad_priority_weight_check CHECK ((priority_weight >= 0))
);


ALTER TABLE public.custom_ads_customad OWNER TO dealnux_user;

--
-- Name: custom_ads_customad_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.custom_ads_customad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_ads_customad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO dealnux_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO dealnux_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO dealnux_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO dealnux_user;

--
-- Name: policy_cookie_policy; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.policy_cookie_policy (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL
);


ALTER TABLE public.policy_cookie_policy OWNER TO dealnux_user;

--
-- Name: policy_cookie_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.policy_cookie_policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_cookie_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: policy_privacy_policy; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.policy_privacy_policy (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL
);


ALTER TABLE public.policy_privacy_policy OWNER TO dealnux_user;

--
-- Name: policy_privacy_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.policy_privacy_policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_privacy_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: policy_terms_of_service; Type: TABLE; Schema: public; Owner: dealnux_user
--

CREATE TABLE public.policy_terms_of_service (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_updated timestamp with time zone NOT NULL
);


ALTER TABLE public.policy_terms_of_service OWNER TO dealnux_user;

--
-- Name: policy_terms_of_service_id_seq; Type: SEQUENCE; Schema: public; Owner: dealnux_user
--

ALTER TABLE public.policy_terms_of_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_terms_of_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_profile; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.account_profile (id, address, interests, profile_picture, user_id) FROM stdin;
\.


--
-- Data for Name: account_user; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.account_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, name, address, ads_provided, referral_code, balance, has_claimed_referral, referred_by_id, otp, profile_setup_completed) FROM stdin;
1	pbkdf2_sha256$1000000$WEGHCNVxn7nkg6LbTeaKj8$uh6ZRMoLKgQPnRWRkoKTi0VESUZrfaqTJVqh4XqBbBU=	\N	t			t	f	2026-02-16 19:01:51.159076+00	admin@gmail.com		\N	f	0CED9399	0.00	f	\N	\N	f
\.


--
-- Data for Name: account_user_groups; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.account_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: account_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.account_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: api_integration_category; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_category (id, name, slug, created_at, updated_at, parent_id) FROM stdin;
\.


--
-- Data for Name: api_integration_platform; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_platform (id, name, code, logo, api_enabled, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: api_integration_pricehistory; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_pricehistory (id, price, currency, recorded_at, listing_id) FROM stdin;
\.


--
-- Data for Name: api_integration_product; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_product (id, title, slug, description, brand, model_number, main_image, is_active, created_at, updated_at, last_synced, category_id) FROM stdin;
\.


--
-- Data for Name: api_integration_productimage; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_productimage (id, image_url, alt_text, "order", created_at, product_id) FROM stdin;
\.


--
-- Data for Name: api_integration_productlisting; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_productlisting (id, external_id, external_url, price, currency, original_price, discount_percentage, condition, quantity, seller_username, seller_rating, seller_feedback_count, item_location, ships_from_country, shipping_cost, shipping_currency, free_shipping, estimated_delivery_days, returns_accepted, return_period_days, is_available, last_checked, created_at, updated_at, platform_id, product_id) FROM stdin;
\.


--
-- Data for Name: api_integration_productspecification; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.api_integration_productspecification (id, name, value, created_at, product_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add profile	7	add_profile
26	Can change profile	7	change_profile
27	Can delete profile	7	delete_profile
28	Can view profile	7	view_profile
29	Can add advertiser request	8	add_advertiserrequest
30	Can change advertiser request	8	change_advertiserrequest
31	Can delete advertiser request	8	delete_advertiserrequest
32	Can view advertiser request	8	view_advertiserrequest
33	Can add custom ad	9	add_customad
34	Can change custom ad	9	change_customad
35	Can delete custom ad	9	delete_customad
36	Can view custom ad	9	view_customad
37	Can add ad review	10	add_adreview
38	Can change ad review	10	change_adreview
39	Can delete ad review	10	delete_adreview
40	Can view ad review	10	view_adreview
41	Can add cookie_ policy	11	add_cookie_policy
42	Can change cookie_ policy	11	change_cookie_policy
43	Can delete cookie_ policy	11	delete_cookie_policy
44	Can view cookie_ policy	11	view_cookie_policy
45	Can add privacy_ policy	12	add_privacy_policy
46	Can change privacy_ policy	12	change_privacy_policy
47	Can delete privacy_ policy	12	delete_privacy_policy
48	Can view privacy_ policy	12	view_privacy_policy
49	Can add terms_ of_ service	13	add_terms_of_service
50	Can change terms_ of_ service	13	change_terms_of_service
51	Can delete terms_ of_ service	13	delete_terms_of_service
52	Can view terms_ of_ service	13	view_terms_of_service
53	Can add platform	14	add_platform
54	Can change platform	14	change_platform
55	Can delete platform	14	delete_platform
56	Can view platform	14	view_platform
57	Can add category	15	add_category
58	Can change category	15	change_category
59	Can delete category	15	delete_category
60	Can view category	15	view_category
61	Can add product	16	add_product
62	Can change product	16	change_product
63	Can delete product	16	delete_product
64	Can view product	16	view_product
65	Can add product image	17	add_productimage
66	Can change product image	17	change_productimage
67	Can delete product image	17	delete_productimage
68	Can view product image	17	view_productimage
69	Can add product listing	18	add_productlisting
70	Can change product listing	18	change_productlisting
71	Can delete product listing	18	delete_productlisting
72	Can view product listing	18	view_productlisting
73	Can add price history	19	add_pricehistory
74	Can change price history	19	change_pricehistory
75	Can delete price history	19	delete_pricehistory
76	Can view price history	19	view_pricehistory
77	Can add product specification	20	add_productspecification
78	Can change product specification	20	change_productspecification
79	Can delete product specification	20	delete_productspecification
80	Can view product specification	20	view_productspecification
\.


--
-- Data for Name: custom_ads_adreview; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.custom_ads_adreview (id, status, feedback, reviewed_at, ad_id, reviewer_id) FROM stdin;
\.


--
-- Data for Name: custom_ads_advertiserrequest; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.custom_ads_advertiserrequest (id, business_name, business_details, website, applied_at, is_reviewed, reviewed_at, rejection_reason, user_id) FROM stdin;
\.


--
-- Data for Name: custom_ads_customad; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.custom_ads_customad (id, title, description, image, target_url, total_budget, spent_amount, priority_weight, is_premium, clicks, impressions, start_date, end_date, is_approved, status, cta_text, created_at, updated_at, advertiser_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	account	user
7	account	profile
8	custom_ads	advertiserrequest
9	custom_ads	customad
10	custom_ads	adreview
11	policy	cookie_policy
12	policy	privacy_policy
13	policy	terms_of_service
14	api_integration	platform
15	api_integration	category
16	api_integration	product
17	api_integration	productimage
18	api_integration	productlisting
19	api_integration	pricehistory
20	api_integration	productspecification
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-16 19:00:56.238768+00
2	contenttypes	0002_remove_content_type_name	2026-02-16 19:00:56.24664+00
3	auth	0001_initial	2026-02-16 19:00:56.280638+00
4	auth	0002_alter_permission_name_max_length	2026-02-16 19:00:56.284678+00
5	auth	0003_alter_user_email_max_length	2026-02-16 19:00:56.288835+00
6	auth	0004_alter_user_username_opts	2026-02-16 19:00:56.292146+00
7	auth	0005_alter_user_last_login_null	2026-02-16 19:00:56.29576+00
8	auth	0006_require_contenttypes_0002	2026-02-16 19:00:56.296899+00
9	auth	0007_alter_validators_add_error_messages	2026-02-16 19:00:56.300263+00
10	auth	0008_alter_user_username_max_length	2026-02-16 19:00:56.303906+00
11	auth	0009_alter_user_last_name_max_length	2026-02-16 19:00:56.307402+00
12	auth	0010_alter_group_name_max_length	2026-02-16 19:00:56.313992+00
13	auth	0011_update_proxy_permissions	2026-02-16 19:00:56.317769+00
14	auth	0012_alter_user_first_name_max_length	2026-02-16 19:00:56.321755+00
15	account	0001_initial	2026-02-16 19:00:56.366229+00
16	account	0002_remove_user_membership_expiry	2026-02-16 19:00:56.372864+00
17	account	0003_rename_full_name_user_fullname	2026-02-16 19:00:56.378643+00
18	account	0004_user_ads_provided_alter_user_is_active	2026-02-16 19:00:56.389174+00
19	account	0005_rename_fullname_user_name	2026-02-16 19:00:56.396407+00
20	account	0006_user_referral_code	2026-02-16 19:00:56.409709+00
21	account	0007_user_balance_user_has_claimed_referral	2026-02-16 19:00:56.421086+00
22	account	0008_user_referred_by	2026-02-16 19:00:56.429479+00
23	account	0009_remove_profile_otp_user_otp_and_more	2026-02-16 19:00:56.442181+00
24	admin	0001_initial	2026-02-16 19:00:56.459884+00
25	admin	0002_logentry_remove_auto_add	2026-02-16 19:00:56.467686+00
26	admin	0003_logentry_add_action_flag_choices	2026-02-16 19:00:56.476535+00
27	api_integration	0001_initial	2026-02-16 19:00:56.650028+00
28	custom_ads	0001_initial	2026-02-16 19:00:56.68719+00
29	custom_ads	0002_adreview	2026-02-16 19:00:56.707162+00
30	policy	0001_initial	2026-02-16 19:00:56.721808+00
31	sessions	0001_initial	2026-02-16 19:00:56.734297+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
9cimgduuzworpg7j2urf3aa10sp82jc3	.eJxVjDsOwjAQBe_iGlkbxx9CSc8ZrN31GgeQI8VJhbg7iZQC2pl5760irkuJa5M5jkldlFGnX0bIT6m7SA-s90nzVJd5JL0n-rBN36Ykr-vR_h0UbGVbZ4PJdJ6pBx9CdsYGwjDYxAJhI9B7Gc7Y-UxkHEsmQAMEDsAG4aw-X9--N_E:1vrLwM:x5yEjL_Zx4lSnxKgbqgZTJBWJUqnd-dll0UDJ5_KyeM	2026-02-28 20:08:30.706869+00
\.


--
-- Data for Name: policy_cookie_policy; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.policy_cookie_policy (id, content, created_at, last_updated) FROM stdin;
\.


--
-- Data for Name: policy_privacy_policy; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.policy_privacy_policy (id, content, created_at, last_updated) FROM stdin;
\.


--
-- Data for Name: policy_terms_of_service; Type: TABLE DATA; Schema: public; Owner: dealnux_user
--

COPY public.policy_terms_of_service (id, content, created_at, last_updated) FROM stdin;
\.


--
-- Name: account_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.account_profile_id_seq', 1, false);


--
-- Name: account_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.account_user_groups_id_seq', 1, false);


--
-- Name: account_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.account_user_id_seq', 4, true);


--
-- Name: account_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.account_user_user_permissions_id_seq', 1, false);


--
-- Name: api_integration_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_category_id_seq', 1, false);


--
-- Name: api_integration_platform_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_platform_id_seq', 1, false);


--
-- Name: api_integration_pricehistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_pricehistory_id_seq', 1, false);


--
-- Name: api_integration_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_product_id_seq', 1, false);


--
-- Name: api_integration_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_productimage_id_seq', 1, false);


--
-- Name: api_integration_productlisting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_productlisting_id_seq', 1, false);


--
-- Name: api_integration_productspecification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.api_integration_productspecification_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: custom_ads_adreview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.custom_ads_adreview_id_seq', 1, false);


--
-- Name: custom_ads_advertiserrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.custom_ads_advertiserrequest_id_seq', 1, false);


--
-- Name: custom_ads_customad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.custom_ads_customad_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: policy_cookie_policy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.policy_cookie_policy_id_seq', 1, false);


--
-- Name: policy_privacy_policy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.policy_privacy_policy_id_seq', 1, false);


--
-- Name: policy_terms_of_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dealnux_user
--

SELECT pg_catalog.setval('public.policy_terms_of_service_id_seq', 1, false);


--
-- Name: account_profile account_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_profile
    ADD CONSTRAINT account_profile_pkey PRIMARY KEY (id);


--
-- Name: account_profile account_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_profile
    ADD CONSTRAINT account_profile_user_id_key UNIQUE (user_id);


--
-- Name: account_user account_user_email_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_email_key UNIQUE (email);


--
-- Name: account_user_groups account_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_pkey PRIMARY KEY (id);


--
-- Name: account_user_groups account_user_groups_user_id_group_id_4d09af3e_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_user_id_group_id_4d09af3e_uniq UNIQUE (user_id, group_id);


--
-- Name: account_user account_user_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_pkey PRIMARY KEY (id);


--
-- Name: account_user account_user_referral_code_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_referral_code_key UNIQUE (referral_code);


--
-- Name: account_user_user_permissions account_user_user_permis_user_id_permission_id_48bdd28b_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_permis_user_id_permission_id_48bdd28b_uniq UNIQUE (user_id, permission_id);


--
-- Name: account_user_user_permissions account_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: api_integration_category api_integration_category_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_category
    ADD CONSTRAINT api_integration_category_pkey PRIMARY KEY (id);


--
-- Name: api_integration_category api_integration_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_category
    ADD CONSTRAINT api_integration_category_slug_key UNIQUE (slug);


--
-- Name: api_integration_platform api_integration_platform_code_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_platform
    ADD CONSTRAINT api_integration_platform_code_key UNIQUE (code);


--
-- Name: api_integration_platform api_integration_platform_name_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_platform
    ADD CONSTRAINT api_integration_platform_name_key UNIQUE (name);


--
-- Name: api_integration_platform api_integration_platform_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_platform
    ADD CONSTRAINT api_integration_platform_pkey PRIMARY KEY (id);


--
-- Name: api_integration_pricehistory api_integration_pricehistory_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_pricehistory
    ADD CONSTRAINT api_integration_pricehistory_pkey PRIMARY KEY (id);


--
-- Name: api_integration_product api_integration_product_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_product
    ADD CONSTRAINT api_integration_product_pkey PRIMARY KEY (id);


--
-- Name: api_integration_product api_integration_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_product
    ADD CONSTRAINT api_integration_product_slug_key UNIQUE (slug);


--
-- Name: api_integration_productimage api_integration_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productimage
    ADD CONSTRAINT api_integration_productimage_pkey PRIMARY KEY (id);


--
-- Name: api_integration_productlisting api_integration_productl_platform_id_external_id_6cce5ce4_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productlisting
    ADD CONSTRAINT api_integration_productl_platform_id_external_id_6cce5ce4_uniq UNIQUE (platform_id, external_id);


--
-- Name: api_integration_productlisting api_integration_productlisting_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productlisting
    ADD CONSTRAINT api_integration_productlisting_pkey PRIMARY KEY (id);


--
-- Name: api_integration_productspecification api_integration_products_product_id_name_992d734c_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productspecification
    ADD CONSTRAINT api_integration_products_product_id_name_992d734c_uniq UNIQUE (product_id, name);


--
-- Name: api_integration_productspecification api_integration_productspecification_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productspecification
    ADD CONSTRAINT api_integration_productspecification_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: custom_ads_adreview custom_ads_adreview_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_adreview
    ADD CONSTRAINT custom_ads_adreview_pkey PRIMARY KEY (id);


--
-- Name: custom_ads_advertiserrequest custom_ads_advertiserrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_advertiserrequest
    ADD CONSTRAINT custom_ads_advertiserrequest_pkey PRIMARY KEY (id);


--
-- Name: custom_ads_advertiserrequest custom_ads_advertiserrequest_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_advertiserrequest
    ADD CONSTRAINT custom_ads_advertiserrequest_user_id_key UNIQUE (user_id);


--
-- Name: custom_ads_customad custom_ads_customad_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_customad
    ADD CONSTRAINT custom_ads_customad_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: policy_cookie_policy policy_cookie_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.policy_cookie_policy
    ADD CONSTRAINT policy_cookie_policy_pkey PRIMARY KEY (id);


--
-- Name: policy_privacy_policy policy_privacy_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.policy_privacy_policy
    ADD CONSTRAINT policy_privacy_policy_pkey PRIMARY KEY (id);


--
-- Name: policy_terms_of_service policy_terms_of_service_pkey; Type: CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.policy_terms_of_service
    ADD CONSTRAINT policy_terms_of_service_pkey PRIMARY KEY (id);


--
-- Name: account_user_email_0bd7c421_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_email_0bd7c421_like ON public.account_user USING btree (email varchar_pattern_ops);


--
-- Name: account_user_groups_group_id_6c71f749; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_groups_group_id_6c71f749 ON public.account_user_groups USING btree (group_id);


--
-- Name: account_user_groups_user_id_14345e7b; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_groups_user_id_14345e7b ON public.account_user_groups USING btree (user_id);


--
-- Name: account_user_referral_code_6af2b827_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_referral_code_6af2b827_like ON public.account_user USING btree (referral_code varchar_pattern_ops);


--
-- Name: account_user_referred_by_id_b946588f; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_referred_by_id_b946588f ON public.account_user USING btree (referred_by_id);


--
-- Name: account_user_user_permissions_permission_id_66c44191; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_user_permissions_permission_id_66c44191 ON public.account_user_user_permissions USING btree (permission_id);


--
-- Name: account_user_user_permissions_user_id_cc42d270; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX account_user_user_permissions_user_id_cc42d270 ON public.account_user_user_permissions USING btree (user_id);


--
-- Name: api_integra_brand_77f276_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integra_brand_77f276_idx ON public.api_integration_product USING btree (brand);


--
-- Name: api_integra_is_avai_1c90fe_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integra_is_avai_1c90fe_idx ON public.api_integration_productlisting USING btree (is_available);


--
-- Name: api_integra_platfor_f5ea11_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integra_platfor_f5ea11_idx ON public.api_integration_productlisting USING btree (platform_id, external_id);


--
-- Name: api_integra_price_02d8f2_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integra_price_02d8f2_idx ON public.api_integration_productlisting USING btree (price);


--
-- Name: api_integra_slug_906d47_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integra_slug_906d47_idx ON public.api_integration_product USING btree (slug);


--
-- Name: api_integra_title_e38c3d_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integra_title_e38c3d_idx ON public.api_integration_product USING btree (title);


--
-- Name: api_integration_category_parent_id_fdee1fe1; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_category_parent_id_fdee1fe1 ON public.api_integration_category USING btree (parent_id);


--
-- Name: api_integration_category_slug_4e62bd32_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_category_slug_4e62bd32_like ON public.api_integration_category USING btree (slug varchar_pattern_ops);


--
-- Name: api_integration_platform_code_1211242b_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_platform_code_1211242b_like ON public.api_integration_platform USING btree (code varchar_pattern_ops);


--
-- Name: api_integration_platform_name_eb895204_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_platform_name_eb895204_like ON public.api_integration_platform USING btree (name varchar_pattern_ops);


--
-- Name: api_integration_pricehistory_listing_id_47a7a170; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_pricehistory_listing_id_47a7a170 ON public.api_integration_pricehistory USING btree (listing_id);


--
-- Name: api_integration_product_category_id_53a05649; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_product_category_id_53a05649 ON public.api_integration_product USING btree (category_id);


--
-- Name: api_integration_product_slug_4611a048_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_product_slug_4611a048_like ON public.api_integration_product USING btree (slug varchar_pattern_ops);


--
-- Name: api_integration_productimage_product_id_0826a571; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_productimage_product_id_0826a571 ON public.api_integration_productimage USING btree (product_id);


--
-- Name: api_integration_productlisting_platform_id_959cc840; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_productlisting_platform_id_959cc840 ON public.api_integration_productlisting USING btree (platform_id);


--
-- Name: api_integration_productlisting_product_id_5c5c5aba; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_productlisting_product_id_5c5c5aba ON public.api_integration_productlisting USING btree (product_id);


--
-- Name: api_integration_productspecification_product_id_470bd373; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX api_integration_productspecification_product_id_470bd373 ON public.api_integration_productspecification USING btree (product_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: custom_ads__status_b39479_idx; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX custom_ads__status_b39479_idx ON public.custom_ads_customad USING btree (status, is_approved, start_date);


--
-- Name: custom_ads_adreview_ad_id_266799cc; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX custom_ads_adreview_ad_id_266799cc ON public.custom_ads_adreview USING btree (ad_id);


--
-- Name: custom_ads_adreview_reviewer_id_97183e47; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX custom_ads_adreview_reviewer_id_97183e47 ON public.custom_ads_adreview USING btree (reviewer_id);


--
-- Name: custom_ads_customad_advertiser_id_75fe023a; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX custom_ads_customad_advertiser_id_75fe023a ON public.custom_ads_customad USING btree (advertiser_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: dealnux_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: account_profile account_profile_user_id_bdd52018_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_profile
    ADD CONSTRAINT account_profile_user_id_bdd52018_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_groups account_user_groups_group_id_6c71f749_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_group_id_6c71f749_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_groups account_user_groups_user_id_14345e7b_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_groups
    ADD CONSTRAINT account_user_groups_user_id_14345e7b_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user account_user_referred_by_id_b946588f_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_referred_by_id_b946588f_fk_account_user_id FOREIGN KEY (referred_by_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_user_permissions account_user_user_pe_permission_id_66c44191_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_pe_permission_id_66c44191_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_user_user_permissions account_user_user_pe_user_id_cc42d270_fk_account_u; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.account_user_user_permissions
    ADD CONSTRAINT account_user_user_pe_user_id_cc42d270_fk_account_u FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_category api_integration_cate_parent_id_fdee1fe1_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_category
    ADD CONSTRAINT api_integration_cate_parent_id_fdee1fe1_fk_api_integ FOREIGN KEY (parent_id) REFERENCES public.api_integration_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_pricehistory api_integration_pric_listing_id_47a7a170_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_pricehistory
    ADD CONSTRAINT api_integration_pric_listing_id_47a7a170_fk_api_integ FOREIGN KEY (listing_id) REFERENCES public.api_integration_productlisting(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_product api_integration_prod_category_id_53a05649_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_product
    ADD CONSTRAINT api_integration_prod_category_id_53a05649_fk_api_integ FOREIGN KEY (category_id) REFERENCES public.api_integration_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_productlisting api_integration_prod_platform_id_959cc840_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productlisting
    ADD CONSTRAINT api_integration_prod_platform_id_959cc840_fk_api_integ FOREIGN KEY (platform_id) REFERENCES public.api_integration_platform(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_productimage api_integration_prod_product_id_0826a571_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productimage
    ADD CONSTRAINT api_integration_prod_product_id_0826a571_fk_api_integ FOREIGN KEY (product_id) REFERENCES public.api_integration_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_productspecification api_integration_prod_product_id_470bd373_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productspecification
    ADD CONSTRAINT api_integration_prod_product_id_470bd373_fk_api_integ FOREIGN KEY (product_id) REFERENCES public.api_integration_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_integration_productlisting api_integration_prod_product_id_5c5c5aba_fk_api_integ; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.api_integration_productlisting
    ADD CONSTRAINT api_integration_prod_product_id_5c5c5aba_fk_api_integ FOREIGN KEY (product_id) REFERENCES public.api_integration_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_ads_adreview custom_ads_adreview_ad_id_266799cc_fk_custom_ads_customad_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_adreview
    ADD CONSTRAINT custom_ads_adreview_ad_id_266799cc_fk_custom_ads_customad_id FOREIGN KEY (ad_id) REFERENCES public.custom_ads_customad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_ads_adreview custom_ads_adreview_reviewer_id_97183e47_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_adreview
    ADD CONSTRAINT custom_ads_adreview_reviewer_id_97183e47_fk_account_user_id FOREIGN KEY (reviewer_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_ads_advertiserrequest custom_ads_advertise_user_id_d49ed481_fk_account_u; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_advertiserrequest
    ADD CONSTRAINT custom_ads_advertise_user_id_d49ed481_fk_account_u FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_ads_customad custom_ads_customad_advertiser_id_75fe023a_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.custom_ads_customad
    ADD CONSTRAINT custom_ads_customad_advertiser_id_75fe023a_fk_account_user_id FOREIGN KEY (advertiser_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_account_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dealnux_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict dFDP4doLarASn0gtGox2kZWA87Tg9ZL72D9nkKXxlvP4KxZHN86fgrcAofloam8

