services:
  web:
    build:
      context: .
      cache_from:
        - dealnux-backend
    image: dealnux-backend
    container_name: dealnux_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: dealnux_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: dealnux_redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    image: dealnux-backend
    container_name: dealnux_celery_worker
    restart: always
    command: celery -A dealnux worker -l info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    image: dealnux-backend
    container_name: dealnux_celery_beat
    restart: always
    command: celery -A dealnux beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: