# Generated by Django 5.2.10 on 2026-04-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ads', '0009_alter_customad_image'),
        ('payment', '0002_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='custom_ads.customad'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('STORE', 'Store Product'), ('AD', 'Custom Ad')], default='STORE', max_length=20),
        ),
    ]
