# Generated by Django 5.2.10 on 2026-05-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_item_total_payment_service_fee_and_more'),
        ('store', '0014_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='Stripe Transfer', max_length=50)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_records', to='store.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
