# Generated by Django 5.2.10 on 2026-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payoutrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_use_cart',
            new_name='has_ai_optimization',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_compare_prices',
            new_name='has_barcode_scanning',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='free_trial_days',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_trial_enabled',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_searches_per_day',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='clicks_per_day',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_alerts_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='daily_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_click_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Trial'), ('PRO_MONTHLY', 'Dealnux PRO'), ('PRO_MAX_YEARLY', 'Dealnux PRO MAX'), ('ULTIMATE_MONTHLY', 'Dealnux ULTIMATE'), ('ULTIMANIA_YEARLY', 'Dealnux ULTIMANIA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
