# Generated by Django 5.2.10 on 2026-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_can_use_cart_subscriptionplan_has_ai_optimization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='How long is the free trial?'),
        ),
    ]
