# Generated by Django 5.2.10 on 2026-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_subscriptionplan_trial_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
