# Generated by Django 5.2.10 on 2026-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_subscriptionplan_trial_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
