# Generated by Django 5.2.10 on 2026-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_usersubscription_trial_ends_at'),
    ]

    operations = [
    ]
