# Generated by Django 5.2.10 on 2026-05-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_subscriptionplan_features_and_more'),
        ('payment', '0009_subscriptionplan_features'),
    ]

    operations = [
    ]
