# Generated by Django 5.2.10 on 2026-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
