# Generated by Django 5.2.10 on 2026-07-29 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_payment_balance_used'),
        ('store', '0020_remove_sellerrequest_return_policy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='store.order'),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payment.payment'),
        ),
    ]
