# Generated by Django 5.2.10 on 2026-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_sellerpayout_order_alter_sellerpayout_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, help_text='Apple App Store Product ID (e.g. com.dealnux.app.premium.monthly)', max_length=200),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='apple_latest_transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='apple_original_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_gateway',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('APPLE', 'Apple'), ('FREE', 'Free Trial')], default='STRIPE', max_length=20),
        ),
    ]
