# Generated by Django 5.2.10 on 2026-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_logo', models.ImageField(blank=True, null=True, upload_to='press/logos/')),
                ('published_date', models.DateField()),
                ('excerpt', models.TextField()),
                ('article_url', models.URLField()),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-published_date'],
            },
        ),
    ]
