# Generated by Django 5.2.10 on 2026-05-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presscoverage',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='presscoverage',
            name='order',
        ),
    ]
