# Generated by Django 5.2.10 on 2026-06-03 10:25

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSliderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='টাইটেল (Admin-এ দেখার জন্য)')),
                ('image', models.ImageField(help_text='সাইজ: 920 × 460 px | Ratio: 2:1 | JPG/PNG/WEBP', upload_to='banners/main/', validators=[homepage.models.validate_main_banner], verbose_name='ইমেজ  [ 920 × 460 px ]')),
                ('link_url', models.URLField(blank=True, help_text='খালি রাখলে কোথাও যাবে না', null=True, verbose_name='লিংক (ক্লিক করলে যাবে)')),
                ('order', models.PositiveIntegerField(default=0, help_text='ছোট সংখ্যা আগে দেখাবে  (1, 2, 3, 4, 5)', verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Slider Banner',
                'verbose_name_plural': 'Main Slider Banners  [ 920×460 px | max 5 ]',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SideBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='টাইটেল (Admin-এ দেখার জন্য)')),
                ('image', models.ImageField(help_text='সাইজ: 299 × 220 px | Ratio: 1.36:1 | JPG/PNG/WEBP', upload_to='banners/side/', validators=[homepage.models.validate_side_banner], verbose_name='ইমেজ  [ 299 × 220 px ]')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Position 1  →  উপরে বাঁয়ে  (Top Left)'), (2, 'Position 2  →  উপরে ডানে   (Top Right)'), (3, 'Position 3  →  নিচে বাঁয়ে  (Bottom Left)'), (4, 'Position 4  →  নিচে ডানে   (Bottom Right)')], help_text='কোন স্লটে দেখাবে?', verbose_name='Position')),
                ('link_url', models.URLField(blank=True, help_text='খালি রাখলে কোথাও যাবে না', null=True, verbose_name='লিংক (ক্লিক করলে যাবে)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Side Banner',
                'verbose_name_plural': 'Side Banners  [ 299×220 px | 4 Positions ]',
                'ordering': ['position'],
            },
        ),
    ]
