# Generated by Django 5.2.10 on 2026-06-03 10:34

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsliderbanner',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Main Slider Banner', 'verbose_name_plural': 'Main Slider Banners  [ 920x460 px | max 5 ]'},
        ),
        migrations.AlterModelOptions(
            name='sidebanner',
            options={'ordering': ['position'], 'verbose_name': 'Side Banner', 'verbose_name_plural': 'Side Banners  [ 299x220 px | 4 Positions ]'},
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='image',
            field=models.ImageField(help_text='Required: 920 x 460 px | Ratio: 2:1 | JPG / PNG / WEBP', upload_to='banners/main/', validators=[homepage.models.validate_main_banner], verbose_name='Image  [ 920 x 460 px ]'),
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='link_url',
            field=models.URLField(blank=True, help_text='Clicking the banner will open this URL. Leave blank for no link.', null=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first  (1, 2, 3, 4, 5)', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='title',
            field=models.CharField(help_text='Internal label — not shown on the homepage.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='mainsliderbanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='image',
            field=models.ImageField(help_text='Required: 299 x 220 px | Ratio: 1.36:1 | JPG / PNG / WEBP', upload_to='banners/side/', validators=[homepage.models.validate_side_banner], verbose_name='Image  [ 299 x 220 px ]'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='link_url',
            field=models.URLField(blank=True, help_text='Clicking the banner will open this URL. Leave blank for no link.', null=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Position 1  →  Top Left'), (2, 'Position 2  →  Top Right'), (3, 'Position 3  →  Bottom Left'), (4, 'Position 4  →  Bottom Right')], help_text='Which slot should this banner appear in?', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='title',
            field=models.CharField(help_text='Internal label — not shown on the homepage.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sidebanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
