# Generated by Django 5.2.10 on 2026-06-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_mainsliderbanner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsliderbanner',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='sidebanner',
            name='link_url',
        ),
    ]
