# Generated by Django 5.2.10 on 2026-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_mainsliderbanner_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderbanner',
            name='link_url',
            field=models.URLField(blank=True, help_text='Clicking the banner will open this URL. Leave blank for no link.', null=True, verbose_name='Link URL'),
        ),
        migrations.AddField(
            model_name='sidebanner',
            name='link_url',
            field=models.URLField(blank=True, help_text='Clicking the banner will open this URL. Leave blank for no link.', null=True, verbose_name='Link URL'),
        ),
    ]
