# Generated by ChatGPT - data migration for default platforms
from django.db import migrations


from django.db import IntegrityError

def create_platforms(apps, schema_editor):
    Platform = apps.get_model('api_integration', 'Platform')
    defaults = [
        {'code': 'ebay', 'name': 'eBay'},
        {'code': 'clickbank', 'name': 'ClickBank'},
        {'code': 'walmart', 'name': 'Walmart'},
        {'code': 'amazon', 'name': 'Amazon'},
        {'code': 'shopify', 'name': 'Shopify'},
    ]
    for vals in defaults:
        try:
            # prefer update_or_create so existing rows are updated
            Platform.objects.update_or_create(
                code=vals['code'],
                defaults={
                    'name': vals['name'],
                    'api_enabled': True,
                }
            )
        except IntegrityError:
            # name may already exist with a different code, fix it manually
            existing = Platform.objects.filter(name=vals['name']).first()
            if existing:
                existing.code = vals['code']
                existing.api_enabled = True
                existing.save()
            else:
                raise


def remove_platforms(apps, schema_editor):
    Platform = apps.get_model('api_integration', 'Platform')
    Platform.objects.filter(code__in=['ebay','clickbank','walmart','amazon','shopify']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_platforms, reverse_code=remove_platforms),
    ]
