# Generated by Django 5.2.10 on 2026-02-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
