# Generated by ChatGPT to resolve migration conflict between 0002_add_default_platforms and 0004_savingsactivity
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0002_add_default_platforms'),
        ('api_integration', '0004_savingsactivity'),
    ]

    operations = []
