# Generated by Django 5.2.10 on 2026-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0005_merge_platforms_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
