# Generated by Django 5.2.10 on 2026-03-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0007_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_listing',
        ),
    ]
