# Generated by Django 5.2.10 on 2026-04-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
