# Generated by Django 5.2.10 on 2026-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0010_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='coupon_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='deal_badge',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='deal_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='has_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
