# Generated by Django 5.2.10 on 2026-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0011_productlisting_coupon_text_productlisting_deal_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
