# Generated by Django 5.2.10 on 2026-04-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0012_product_rating_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
