# Generated by Django 5.2.10 on 2026-04-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0013_alter_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
