# Generated by Django 5.2.10 on 2026-07-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0015_notification_pricealert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
