# Generated by Django 5.2.10 on 2026-08-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='role',
            field=models.CharField(choices=[('Product Manager', 'Product Manager'), ('Data Analyst', 'Data Analyst'), ('Digital Marketing Specialist', 'Digital Marketing Specialist'), ('Customer Support Specialist', 'Customer Support Specialist'), ('Sales Executive', 'Sales Executive'), ('Other', 'Other'), ('product_manager', 'Product Manager'), ('data_analyst', 'Data Analyst'), ('digital_marketing_specialist', 'Digital Marketing Specialist'), ('customer_support_specialist', 'Customer Support Specialist'), ('sales_executive', 'Sales Executive'), ('other', 'Other'), ('admin', 'Admin'), ('staff', 'Staff'), ('moderator', 'Moderator'), ('support', 'Customer Support')], max_length=50),
        ),
    ]
