# Generated by Django 5.2.10 on 2026-06-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ticket_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
    ]
