"""
Django settings for dealnux project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from datetime import datetime
from dotenv import load_dotenv
from decouple import config
from celery.schedules import crontab

import api_integration


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# .env file loading
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


def get_env_list(var_name, default=""):
    value = os.getenv(var_name, default)
    if not value:
        return []

    return [item.strip() for item in value.split(",") if item.strip()]


# Security settings
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'


# default to empty list; use environment variable to specify hosts in production
ALLOWED_HOSTS = get_env_list('ALLOWED_HOSTS', '')
CORS_ALLOWED_ORIGINS = get_env_list('CORS_ALLOWED_ORIGINS')
CSRF_TRUSTED_ORIGINS = get_env_list('CSRF_TRUSTED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# additional security hardening
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_HTTPONLY = True

# redirect HTTP to HTTPS when enabled
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
# HSTS settings
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'

# browser protections
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'

# X_FRAME_OPTIONS is enforced by middleware but can be set explicitly
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',



    # Local apps
    'account',
    'custom_ads',
    'policy',
    'notifications',
    'api_integration',
    'store',
    'payment',
    'blog',
    'career',
    'pages',
    'homepage',


    # Third-party apps
    'corsheaders',
    'rest_framework',
    'drf_spectacular',

]

AUTH_USER_MODEL = 'account.User'



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'FETCH_USERINFO': True,
    },
    'apple': {
        'APP': {
            'client_id': os.environ.get('APPLE_CLIENT_ID'),
            'secret': os.environ.get('APPLE_PRIVATE_KEY'),
            'key': os.environ.get('APPLE_KEY_ID'),
            'certificate_key': os.environ.get('APPLE_PRIVATE_KEY')
        },
        'TEAM_ID': os.environ.get('APPLE_TEAM_ID'),
    }
}

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api_integration.utils.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # default permissions should require authentication; override in individual views
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # rate limiting to protect endpoints from abuse
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.UserRateThrottle',
    #     'rest_framework.throttling.AnonRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'user': '1000/day',
    #     'anon': '100/day',
    # },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': None,
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}


# ==================== JWT & Session Settings ====================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=90),    # Extended from 10 days to 90 days for maximum session persistence
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# Persistent Session Settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 90  # 90 Days session cookie
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dealnux.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

from .unfold_conf import UNFOLD_CONFIG
UNFOLD = UNFOLD_CONFIG

# Add this to settings.py


# WSGI_APPLICATION = 'dealnux.wsgi.application'
ASGI_APPLICATION = 'dealnux.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')

CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TIME_LIMIT = 300  
CELERY_TASK_SOFT_TIME_LIMIT = 240 

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

CELERY_BEAT_SCHEDULE = {
    'daily-category-sync': {
        'task': 'api_integration.tasks.safe_category_sync',
        'schedule': crontab(hour=2, minute=0), 
    },
    'process-scheduled-notifications': {
        'task': 'notifications.tasks.send_scheduled_notifications',
        'schedule': crontab(minute='*'),  # Run every minute
    },
    'daily-subscription-reminders': {
        'task': 'notifications.tasks.send_subscription_reminders',
        'schedule': crontab(hour=9, minute=0),  # Run daily at 9:00 AM
    },
    'daily-ai-recommendations': {
        'task': 'notifications.tasks.send_daily_ai_recommendations',
        'schedule': crontab(hour=10, minute=0),  # Run daily at 10:00 AM
    },
}

# CELERY_BEAT_SCHEDULE = {
#     'hourly-category-sync': {
#         'task': 'api_integration.tasks.safe_category_sync',
#         'schedule': crontab(minute=0, hour='*/24'),
#     },
# }
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static_local',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')

EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL')
SITE_URL = os.environ.get('SITE_URL')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET')
GOOGLE_OAUTH2_REDIRECT_URI = os.getenv('GOOGLE_OAUTH2_REDIRECT_URI')


# revinewcat credential
REVENUECAT_API_KEY = os.getenv('REVENUECAT_API_KEY')
REVENUECAT_WEBHOOK_AUTH_HEADER = os.getenv('REVENUECAT_WEBHOOK_AUTH_HEADER')

RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY')


STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_SUCCESS_URL = os.getenv('STRIPE_SUCCESS_URL')
STRIPE_CANCEL_URL = os.getenv('STRIPE_CANCEL_URL')
STRIPE_CONNECT_REFRESH_URL = os.getenv('STRIPE_CONNECT_REFRESH_URL')
STRIPE_CONNECT_RETURN_URL = os.getenv('STRIPE_CONNECT_RETURN_URL')
STRIPE_RETURN_URL = 'https://www.dealnux.shop/payment/success'


# HTTPS Fix for Nginx Reverse Proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AI_ENGINE_URL = "http://dealnux-ai--web-1:8001"
# Product sync schedules - Added
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE.update({
    'sync-ebay': {
        'task': 'api_integration.tasks.sync_ebay_task',
        'schedule': crontab(hour=9, minute=0),
    },
    'sync-amazon': {
        'task': 'api_integration.tasks.sync_amazon_task',
        'schedule': crontab(hour=10, minute=0),
    },
    'sync-walmart': {
        'task': 'api_integration.tasks.sync_walmart_task',
        'schedule': crontab(hour=11, minute=0),
    },
    'sync-target': {
        'task': 'api_integration.tasks.sync_target_task',
        'schedule': crontab(hour=12, minute=0),
    },
    'sync-aliexpress': {
        'task': 'api_integration.tasks.sync_aliexpress_task',
        'schedule': crontab(hour=5, minute=0, day_of_week='mon,thu'),
    },
    'sync-bestbuy': {
        'task': 'api_integration.tasks.sync_bestbuy_task',
        'schedule': crontab(hour=13, minute=0),
    },
    'sync-wayfair': {
        'task': 'api_integration.tasks.sync_wayfair_task',
        'schedule': crontab(hour=14, minute=0),
    },
    'sync-sephora': {
        'task': 'api_integration.tasks.sync_sephora_task',
        'schedule': crontab(hour=3, minute=0),
    },
})


DOCS_USERNAME = os.environ.get('DOCS_USERNAME', 'docsuser')
DOCS_PASSWORD = os.environ.get('DOCS_PASSWORD', 'changeme')