"""
Django settings for dealnux project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from decouple import config

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# .env ফাইল লোড করা
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def get_env_list(var_name, default=""):
    value = os.getenv(var_name, default)
    if not value:
        return []
    # স্পেস ট্রিম করা এবং খালি স্ট্রিং ফিল্টার করা
    return [item.strip() for item in value.split(",") if item.strip()]

# Security settings
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# সংশোধিত লিস্ট হ্যান্ডলিং
ALLOWED_HOSTS = get_env_list('ALLOWED_HOSTS', '*')
CORS_ALLOWED_ORIGINS = get_env_list('CORS_ALLOWED_ORIGINS')
CSRF_TRUSTED_ORIGINS = get_env_list('CSRF_TRUSTED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Local apps
    'account',
    'custom_ads',
    'policy',
    'api_integration',
    

    # Third-party apps
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    
]

AUTH_USER_MODEL = 'account.User'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api_integration.utils.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}


# ==================== JWT ====================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365 * 100),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dealnux.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

UNFOLD = {
    "SITE_TITLE": "Your Site Admin",
    "SITE_HEADER": "Administration",
    "SITE_URL": "/",
    
    "COLORS": {
        "primary": {
            "50": "239 245 255",   # Very light blue
            "100": "219 234 254",  # Lighter blue
            "200": "191 219 254",  # Light blue
            "300": "147 197 253",  # Medium light blue
            "400": "96 165 250",   # Medium blue
            "500": "35 85 182",    # Your main color #2355B6
            "600": "28 68 146",    # Darker shade
            "700": "23 56 120",    # More darker
            "800": "18 45 94",     # Even darker
            "900": "14 35 73",     # Darkest shade
            "950": "10 25 52",     # Ultra dark
        },
    },

    # Sidebar customization
    "SIDEBAR": {
        "show_search": True,  # Search box sidebar-এ
        "show_all_applications": True,
        # "navigation": [
        #     {
        #         "title": "Navigation",
        #         "separator": True,
        #         "items": [
        #             {
        #                 "title": "Dashboard",
        #                 "icon": "dashboard",
        #                 "link": "/admin/",
        #             },
        #         ],
        #     },
        # ],
    },
}

# Add this to settings.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# WSGI_APPLICATION = 'dealnux.wsgi.application'
ASGI_APPLICATION = 'dealnux.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')

EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET')
GOOGLE_OAUTH2_REDIRECT_URI = os.getenv('GOOGLE_OAUTH2_REDIRECT_URI')


# revinewcat credential 
REVENUECAT_API_KEY = os.getenv('REVENUECAT_API_KEY')
REVENUECAT_WEBHOOK_AUTH_HEADER = os.getenv('REVENUECAT_WEBHOOK_AUTH_HEADER')

# eBay API Configuration
EBAY_ENV = config('EBAY_ENV', default='SANDBOX')
EBAY_APP_ID = config('EBAY_APP_ID')
EBAY_CERT_ID = config('EBAY_CERT_ID')
EBAY_DEV_ID = config('EBAY_DEV_ID', default='')

if EBAY_ENV == 'SANDBOX':
    EBAY_BASE_URL = 'https://api.sandbox.ebay.com'
else:
    EBAY_BASE_URL = 'https://api.ebay.com'


# ClickBank API Configuration
CLICKBANK_API_KEY = config('CLICKBANK_API_KEY', default='')
CLICKBANK_DEV_KEY = config('CLICKBANK_DEV_KEY', default='DEV-123456789012345678901234567890123456')

# Amazon API Configuration (future)
# AMAZON_ACCESS_KEY = config('AMAZON_ACCESS_KEY', default='')
# AMAZON_SECRET_KEY = config('AMAZON_SECRET_KEY', default='')

# # AliExpress API Configuration (future)
# ALIEXPRESS_APP_KEY = config('ALIEXPRESS_APP_KEY', default='')
# ALIEXPRESS_APP_SECRET = config('ALIEXPRESS_APP_SECRET', default='')
