# Generated by Django 5.2.10 on 2026-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_channel_notification_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cta_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
